
package lec15_services.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SayWebServiceService", targetNamespace = "http://client/", wsdlLocation = "http://10.233.57.103:8888/ws/server?WSDL")
public class SayWebServiceService
    extends Service
{

    private final static URL SAYWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYWEBSERVICESERVICE_EXCEPTION;
    private final static QName SAYWEBSERVICESERVICE_QNAME = new QName("http://client/", "SayWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.233.57.103:8888/ws/server?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYWEBSERVICESERVICE_WSDL_LOCATION = url;
        SAYWEBSERVICESERVICE_EXCEPTION = e;
    }

    public SayWebServiceService() {
        super(__getWsdlLocation(), SAYWEBSERVICESERVICE_QNAME);
    }

    public SayWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAYWEBSERVICESERVICE_QNAME, features);
    }

    public SayWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SAYWEBSERVICESERVICE_QNAME);
    }

    public SayWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAYWEBSERVICESERVICE_QNAME, features);
    }

    public SayWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SayWebService
     */
    @WebEndpoint(name = "SayWebServicePort")
    public SayWebService getSayWebServicePort() {
        return super.getPort(new QName("http://client/", "SayWebServicePort"), SayWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayWebService
     */
    @WebEndpoint(name = "SayWebServicePort")
    public SayWebService getSayWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client/", "SayWebServicePort"), SayWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYWEBSERVICESERVICE_EXCEPTION!= null) {
            throw SAYWEBSERVICESERVICE_EXCEPTION;
        }
        return SAYWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
